print('Welcom to "Project name generator"')
a = input('What is your first name? \n')
b = input('Describe your progect in one word e.g. "Industries" \n')
print('Our recommended name for your project is: ')
print('"' + a + ' ' + b + '"' )